### ISSUE TITLE
Feature Request for registering Multiple  Geofences.

### ISSUE THREAD

**Issue by GadepalliAditya1998** [bkonyi/FlutterGeofencing#22]
Hey @bkonyi . I would like to request you for a feature for registering multiple geofences at once.  I see no API for adding currently. One more issue is that the Plugin works but the response is a bit slow. It is taking time to trigger events. I wanted to know whether its a normal case or a issue in plugin?

**Comment by bkonyi** [comment]
I'm currently not looking to add functionality to this plugin as it's mostly intended to be an example, but I'm happy to accept pull requests.

Geofencing isn't terribly responsive in general, so that's not an issue unique to this plugin. You might just need to adjust your battery optimization settings for your application (assuming you're on Android) to prevent battery usage optimization while the application is backgrounded. I've done that with my garage door opener application and that seems to make the geofencing events much more consistent.
